/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.pertemuan9.tp9;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    private String username;

    @Override
    public void start(Stage primaryStage) {
        HomeScene homeScene = new HomeScene(primaryStage, this);
        primaryStage.setScene(homeScene.getScene());
        primaryStage.setTitle("Home");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return username;
    }
}
