/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.zainab.tugas;

import java.util.HashMap;
import java.util.Map;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import javafx.geometry.Pos;
import javafx.scene.layout.VBox;
import javafx.scene.layout.HBox;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.StackPane;

public class App extends Application {
    private Map<String, String> userCredentials = new HashMap<>();
    private Map<String, String> userProfiles = new HashMap<>();
    private String currentLoggedInUser;
    private String username;
    private String password;
    private String name;
    private String date;

    @Override
    public void start(Stage stage) throws Exception {
        stage.setScene(mainMenuScene(stage));
        stage.show();
    }

    private Scene mainMenuScene(Stage stage) {
        Label judul1 = new Label("WELCOME");
        judul1.getStyleClass().add("judul");
    
        Button btn1 = new Button("Login");
        btn1.getStyleClass().add("button");
        btn1.setOnAction(e -> stage.setScene(loginScene(stage)));
    
        Button btn2 = new Button("Register");
        btn2.getStyleClass().add("button");
        btn2.setOnAction(e -> stage.setScene(registerScene(stage)));

        VBox buttonBox = new VBox(10, btn1, btn2);
        buttonBox.setAlignment(Pos.CENTER);

        VBox vbox = new VBox(30, judul1, buttonBox); 
        vbox.setAlignment(Pos.CENTER);
    
        StackPane root = new StackPane(vbox);
        root.getStyleClass().add("latar");
    
        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/Style/Style.css").toExternalForm());
        stage.setTitle("Pinkzy App");
        return scene;
    }

    private Scene registerScene(Stage stage) {
        Label registerLabel = new Label("REGISTER");
        registerLabel.getStyleClass().add("judul");
    
        Label nama1 = new Label("Name:");
        TextField nama2 = new TextField();
        HBox nameBox = new HBox(10, nama1, nama2);
        nameBox.setAlignment(Pos.CENTER);
    
        Label dateLabel = new Label("Birthday:");
        TextField dateField = new TextField();
        HBox dateBox = new HBox(10, dateLabel, dateField);
        dateBox.setAlignment(Pos.CENTER);
    
        Label usernama1 = new Label("Username:");
        TextField usernama2 = new TextField();
        HBox userBox = new HBox(10, usernama1, usernama2);
        userBox.setAlignment(Pos.CENTER);
    
        Label passwordLabel = new Label("Password:");
        PasswordField passwordField = new PasswordField();
        HBox passBox = new HBox(10, passwordLabel, passwordField);
        passBox.setAlignment(Pos.CENTER);
    
        Label salah1 = new Label();
        salah1.getStyleClass().add("error");
    
        Button submit = new Button("Submit");
        submit.getStyleClass().add("buttonS");
        submit.setOnAction(e -> {
            name = nama2.getText();
            date = dateField.getText();
            username = usernama2.getText();
            password = passwordField.getText();
            if (name.isEmpty() || date.isEmpty() || username.isEmpty() || password.isEmpty()) {
                salah1.setText("Please fill in all fields");
            } else if (password.length() < 8) {
                salah1.setText("Password must be at least 8 characters");
            } else {
                userCredentials.put(username, password);
                userProfiles.put(username, name + ", Birthday: " + date);
                stage.setScene(registerSuccess(stage));
            }
        });
    
        Button back = new Button("Back");
        back.getStyleClass().add("buttonS");
        back.setOnAction(e -> stage.setScene(mainMenuScene(stage)));
    
        VBox vbox = new VBox(10, registerLabel, nameBox, dateBox, userBox, passBox, salah1, submit, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.getStyleClass().add("latar");
    
        Scene scene = new Scene(vbox, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/Style/Style.css").toExternalForm());
        return scene;
    }
    

    private Scene registerSuccess(Stage stage) {
        Label success = new Label("Registration Successful");
        success.getStyleClass().add("judul");
        success.relocate(143, 150);

        Button back = new Button("Back");
        back.getStyleClass().add("buttonS");
        back.relocate(270, 250);
        back.setOnAction(e -> stage.setScene(mainMenuScene(stage)));

        Pane root = new Pane();
        root.getChildren().addAll(success, back);
        root.getStyleClass().add("latar");
        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/Style/Style.css").toExternalForm());
        return scene;
    }

    private Scene loginScene(Stage stage) {
        Label loginLabel = new Label("LOGIN");
        loginLabel.getStyleClass().add("judul");
        loginLabel.relocate(250, 100);

        Label usernameLogin1 = new Label("Username:");
        TextField usernameLogin2 = new TextField();
        usernameLogin1.getStyleClass().add("input");
        usernameLogin1.relocate(90, 200);
        usernameLogin2.relocate(190, 200);
        usernameLogin2.getStyleClass().add("tabelInput");

        Label passLogin = new Label("Password\t:");
        PasswordField passwordFieldLogin = new PasswordField();
        passLogin.getStyleClass().add("input");
        passLogin.relocate(90, 240);
        passwordFieldLogin.relocate(190, 240);
        passwordFieldLogin.getStyleClass().add("tabelInput");

        Label salah2 = new Label();
        salah2.getStyleClass().add("error");
        salah2.relocate(190, 300);
        
        Button submit1 = new Button("Submit");
        submit1.getStyleClass().add("buttonS");
        submit1.relocate(440, 300);
        submit1.setOnAction(e -> {
            String username = usernameLogin2.getText();
            String password = passwordFieldLogin.getText();

            if (userCredentials.containsKey(username) && userCredentials.get(username).equals(password)) {
                currentLoggedInUser = username;
                stage.setScene(profileScene(stage));
            } else {
                salah2.setText("Invalid username or password");
                salah2.getStyleClass().add("warning");
                salah2.relocate(360, 267);
            }
        });

        Button back = new Button("Back");
        back.getStyleClass().add("buttonS");
        back.relocate(330, 300);
        back.setOnAction(e -> stage.setScene(mainMenuScene(stage)));

        Pane root = new Pane();
        root.getChildren().addAll(loginLabel, passLogin, passwordFieldLogin, usernameLogin1, usernameLogin2, back, submit1, salah2);
        root.getStyleClass().add("latar");
        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/Style/Style.css").toExternalForm());
        return scene;
    }

    private Scene profileScene(Stage stage) {
        Label profil = new Label("PROFILE");
        profil.getStyleClass().add("judul");
        profil.relocate(250, 100);

        String[] profileDetails = userProfiles.get(currentLoggedInUser).split(", ");
        Label hasilNama = new Label("Name\t: " + profileDetails[0]);
        hasilNama.getStyleClass().add("input");
        hasilNama.relocate(90, 170);

        Label hasilDate = new Label("" + profileDetails[1]);
        hasilDate.getStyleClass().add("input");
        hasilDate.relocate(90, 210);


        Button back = new Button("Back");
        back.getStyleClass().add("buttonS");
        back.relocate(440, 340);
        back.setOnAction(e -> stage.setScene(mainMenuScene(stage)));

        Pane root = new Pane();
        root.getChildren().addAll(profil, back, hasilNama, hasilDate);
        root.getStyleClass().add("latar");
        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/Style/Style.css").toExternalForm());
        return scene;
    }

    public static void main(String[] args) {
        launch(args);
    }
}